=== zhouchaozhong/study_notes/java/javaee/book.dtd
<!ENTITY bookname "javaweb开发">

<!ELEMENT bookshelf (book+)>
<!ELEMENT book (title,author,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== zhouchaozhong/study_notes/java/javaee/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookshelf SYSTEM "book.dtd">
<bookshelf>
    <book>
        <title>编译原理</title>
        <author>屈婉玲</author>
        <price>50.00元</price>
    </book>
    <book>
        <title>数据结构</title>
        <author>张大山</author>
        <price>30.00元</price>
    </book>
    <book>
        <title>&bookname;</title>
        <author>张晓</author>
        <price>60.00元</price>
    </book>
</bookshelf>
